name: Plan

on:
  pull_request:
    branches:
      - main

env:
  tf_version: 1.9.2

jobs:
  plan:
    environment: reader
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
      TF_BUCKET_NAME: bbog-ca-tf-states
      TF_STATE_FILE_NAME: ml.tfstate
    defaults:
      run:
        working-directory: "."
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}
      - name: terraform init
        id: init
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=$TF_BUCKET_NAME" \
            -backend-config="key=$TF_STATE_FILE_NAME" \
            -backend-config="region=$AWS_REGION" \
            -backend-config="encrypt=true"
      - name: terraform fmt
        id: fmt
        run: terraform fmt -check -recursive
      - name: terraform validate
        id: validate
        run: terraform validate
      - name: setup aws-cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: terraform plan
        id: plan
        run: terraform plan -input=false -compact-warnings -var-file=prod.tfvars -out=tfplan
        env:
          TF_VAR_db_credentials_username: ${{ secrets.DB_SECRET_USER }}
          TF_VAR_db_credentials_password: ${{ secrets.DB_SECRET_PASS }}
      - name: terraform show
        id: show
        run: terraform show tfplan

  checkov:
    environment: reader
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_BUCKET_NAME: bbog-ca-tf-states
      TF_STATE_FILE_NAME: ml.tfstate
    defaults:
      run:
        working-directory: "."
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}
      - name: terraform init
        id: init
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=$TF_BUCKET_NAME" \
            -backend-config="key=$TF_STATE_FILE_NAME" \
            -backend-config="region=$AWS_REGION" \
            -backend-config="encrypt=true"
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: "."
          quiet: false
          soft_fail: false
          framework: terraform
